name: Build & Release on Bintray
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        id: setup_java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get Version from Tag Name
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Deploy to Bintray
        id: deploy_bintray
        run: sbt 'set version := "${{ steps.get_version.outputs.VERSION }}"' 'set bintrayRepository := "github"' publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_API_KEY }}